baseURL = 'https://openclawgotchi.github.io/doc/'
languageCode = 'ru-ru'
title = 'Gotchi Bot Docs'
theme = 'simple'

[markup]
  [markup.highlight]
    anchorLineNos = false
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'github-dark'
    tabWidth = 4

[menu]
  [[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 1
  [[menu.main]]
    name = "Articles"
    url = "/articles/"
    weight = 2
  [[menu.main]]
    name = "Dev.to Blog"
    url = "https://dev.to/openclawgotchi/"
    weight = 3
    identifier = "üìù"
    pre = 'target="_blank" rel="noopener"'
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/turmyshevd/openclawgotchi"
    weight = 4
    identifier = "üîó"
    pre = 'target="_blank" rel="noopener"'
